default:
  port: 8080
  debug: true
  # log_dir:
  static_dir: ./static
  admin_username: admin
  admin_password: admin123
database:
  host: 0.0.0.0
  port: 3306
  user: root
  password: 123456
  db_name: pdf_online